apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    tasks:
      - name: test
        taskSpec:
          steps:
            - name: fail-on-purpose
              image: alpine
              script: |
                #!/bin/sh
                echo "This will fail!"
                exit 1
